OrdererOrgs:
  - Name: 'Org0Orderer'
    Domain: 'orderer.org0.example.com'
    EnableNodeOUs: true
    Specs:
      - Hostname: 'orderer0'
      - Hostname: 'orderer1'
PeerOrgs:
  - Name: 'Org0'
    Domain: 'org0.example.com'
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: 'Org1'
    Domain: 'org1.example.com'
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
