version: '3.5'
services:
  peer0.org0.example.com:
    container_name: 'peer0.org0.example.com'
    image: 'hyperledger/fabric-peer:2.2.1'
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - 'CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bdk-fabric-network'
      - 'FABRIC_LOGGING_SPEC=INFO'
      - 'CORE_PEER_TLS_ENABLED=true'
      - 'CORE_PEER_PROFILE_ENABLED=true'
      - 'CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp'
      - 'CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt'
      - 'CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key'
      - 'CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt'
      - 'CORE_PEER_ID=peer0.org0.example.com'
      - 'CORE_PEER_ADDRESS=peer0.org0.example.com:7051'
      - 'CORE_PEER_LISTENADDRESS=0.0.0.0:7051'
      - 'CORE_PEER_CHAINCODEADDRESS=peer0.org0.example.com:7052'
      - 'CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052'
      - 'CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org0.example.com:7051'
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org0.example.com:7051'
      - 'CORE_PEER_LOCALMSPID=Org0'
      - 'CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443'
      - 'CORE_OPERATIONS_TLS_ENABLED=true'
      - 'CORE_OPERATIONS_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt'
      - 'CORE_OPERATIONS_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key'
      - 'CORE_PEER_GOSSIP_USELEADERELECTION=true'
      - 'CORE_PEER_GOSSIP_ORGLEADER=false'
    working_dir: '/opt/gopath/src/github.com/hyperledger/fabric/peer'
    command: 'peer node start'
    volumes:
      - '/var/run/:/host/var/run/'
      - '${BDK_DOCKER_HOST_PATH:-~/.bdk/fabric}/bdk-fabric-network/peerOrganizations/org0.example.com/peers/peer0.org0.example.com/msp:/etc/hyperledger/fabric/msp'
      - '${BDK_DOCKER_HOST_PATH:-~/.bdk/fabric}/bdk-fabric-network/peerOrganizations/org0.example.com/peers/peer0.org0.example.com/tls:/etc/hyperledger/fabric/tls'
      - 'peer0.org0.example.com:/var/hyperledger/production'
    networks:
      - 'bdk-fabric-network'
    ports:
      - '7051:7051'
      - '9443:9443'
volumes:
  peer0.org0.example.com: {}
networks:
  bdk-fabric-network:
    name: 'bdk-fabric-network'
    external: true
