version: '3.5'
services:
  orderer1.orderer.org0.example.com:
    container_name: 'orderer1.orderer.org0.example.com'
    image: 'hyperledger/fabric-orderer:2.2.1'
    environment:
      - 'FABRIC_LOGGING_SPEC=INFO'
      - 'ORDERER_GENERAL_LISTENADDRESS=0.0.0.0'
      - 'ORDERER_GENERAL_LISTENPORT=7150'
      - 'ORDERER_GENERAL_GENESISMETHOD=file'
      - 'ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block'
      - 'ORDERER_GENERAL_LOCALMSPID=Org0Orderer'
      - 'ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp'
      - 'ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8543'
      - 'ORDERER_OPERATIONS_TLS_ENABLED=true'
      - 'ORDERER_OPERATIONS_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt'
      - 'ORDERER_OPERATIONS_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key'
      - 'ORDERER_GENERAL_TLS_ENABLED=true'
      - 'ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key'
      - 'ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt'
      - 'ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]'
      - 'ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt'
      - 'ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key'
      - 'ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]'
    working_dir: '/opt/gopath/src/github.com/hyperledger/fabric'
    command: 'orderer'
    volumes:
      - '${BDK_DOCKER_HOST_PATH:-~/.bdk/fabric}/bdk-fabric-network/channel-artifacts/system-channel/genesis.block:/var/hyperledger/orderer/orderer.genesis.block'
      - '${BDK_DOCKER_HOST_PATH:-~/.bdk/fabric}/bdk-fabric-network/ordererOrganizations/orderer.org0.example.com/orderers/orderer1.orderer.org0.example.com/msp:/var/hyperledger/orderer/msp'
      - '${BDK_DOCKER_HOST_PATH:-~/.bdk/fabric}/bdk-fabric-network/ordererOrganizations/orderer.org0.example.com/orderers/orderer1.orderer.org0.example.com/tls:/var/hyperledger/orderer/tls'
      - 'orderer1.orderer.org0.example.com:/var/hyperledger/production/orderer'
    networks:
      - 'bdk-fabric-network'
    ports:
      - '7150:7150'
      - '8543:8543'
volumes:
  orderer1.orderer.org0.example.com: {}
networks:
  bdk-fabric-network:
    name: 'bdk-fabric-network'
    external: true
